name: Lint
on: pull_request

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update SwiftFormat
        run: brew upgrade swiftformat || true
      - name: SwiftFormat
        run: swiftformat --lint . --reporter github-actions-log
